sudo: false
language: cpp
dist: bionic

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/ppa"
      - sourceline: "ppa:ubuntu-toolchain-r/test"
      - sourceline: "deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
      - g++-9
      - clang-9

env:
  - COMPILER=g++-9
  - COMPILER=clang++-9

script:
  - make CXX=$COMPILER
